/**
 * Insert > Emojis.
 *
 * A curated list rather than the full Unicode emoji set: the whole set is tens
 * of thousands of sequences, most of which no font on a Windows desktop can
 * draw, and shipping it would make the picker slower and worse. These are the
 * ones people actually type into documents, and every one renders in Segoe UI
 * Emoji without downloading anything.
 */
export interface EmojiGroup {
  name: string;
  emoji: Array<{ char: string; name: string }>;
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: 'Smileys',
    emoji: [
      { char: '😀', name: 'grinning face' },
      { char: '😃', name: 'grinning face with big eyes' },
      { char: '😄', name: 'grinning face with smiling eyes' },
      { char: '😁', name: 'beaming face' },
      { char: '😆', name: 'grinning squinting face' },
      { char: '😅', name: 'grinning face with sweat' },
      { char: '🤣', name: 'rolling on the floor laughing' },
      { char: '😂', name: 'face with tears of joy' },
      { char: '🙂', name: 'slightly smiling face' },
      { char: '🙃', name: 'upside-down face' },
      { char: '😉', name: 'winking face' },
      { char: '😊', name: 'smiling face with smiling eyes' },
      { char: '😇', name: 'smiling face with halo' },
      { char: '🥰', name: 'smiling face with hearts' },
      { char: '😍', name: 'heart eyes' },
      { char: '😘', name: 'face blowing a kiss' },
      { char: '😋', name: 'face savouring food' },
      { char: '😜', name: 'winking face with tongue' },
      { char: '🤪', name: 'zany face' },
      { char: '🤨', name: 'face with raised eyebrow' },
      { char: '🧐', name: 'face with monocle' },
      { char: '🤓', name: 'nerd face' },
      { char: '😎', name: 'smiling face with sunglasses' },
      { char: '🥳', name: 'partying face' },
      { char: '😏', name: 'smirking face' },
      { char: '😒', name: 'unamused face' },
      { char: '😞', name: 'disappointed face' },
      { char: '😔', name: 'pensive face' },
      { char: '😟', name: 'worried face' },
      { char: '🙁', name: 'slightly frowning face' },
      { char: '😣', name: 'persevering face' },
      { char: '😖', name: 'confounded face' },
      { char: '😫', name: 'tired face' },
      { char: '😩', name: 'weary face' },
      { char: '🥺', name: 'pleading face' },
      { char: '😢', name: 'crying face' },
      { char: '😭', name: 'loudly crying face' },
      { char: '😤', name: 'face with steam from nose' },
      { char: '😠', name: 'angry face' },
      { char: '😡', name: 'enraged face' },
      { char: '🤯', name: 'exploding head' },
      { char: '😳', name: 'flushed face' },
      { char: '🥵', name: 'hot face' },
      { char: '🥶', name: 'cold face' },
      { char: '😱', name: 'face screaming in fear' },
      { char: '😨', name: 'fearful face' },
      { char: '😰', name: 'anxious face with sweat' },
      { char: '🤔', name: 'thinking face' },
      { char: '🤫', name: 'shushing face' },
      { char: '🤭', name: 'face with hand over mouth' },
      { char: '😐', name: 'neutral face' },
      { char: '😑', name: 'expressionless face' },
      { char: '😶', name: 'face without mouth' },
      { char: '😬', name: 'grimacing face' },
      { char: '🙄', name: 'face with rolling eyes' },
      { char: '😴', name: 'sleeping face' },
      { char: '🤤', name: 'drooling face' },
      { char: '😪', name: 'sleepy face' },
      { char: '🤢', name: 'nauseated face' },
      { char: '🤮', name: 'face vomiting' },
      { char: '🤧', name: 'sneezing face' },
      { char: '😷', name: 'face with medical mask' },
      { char: '🤒', name: 'face with thermometer' },
      { char: '🤕', name: 'face with head bandage' },
      { char: '🥴', name: 'woozy face' },
      { char: '😵', name: 'dizzy face' },
      { char: '🤠', name: 'cowboy hat face' },
      { char: '🤡', name: 'clown face' },
      { char: '👻', name: 'ghost' },
      { char: '💀', name: 'skull' },
      { char: '👽', name: 'alien' },
      { char: '🤖', name: 'robot' },
      { char: '💩', name: 'pile of poo' },
    ],
  },
  {
    name: 'People',
    emoji: [
      { char: '👋', name: 'waving hand' },
      { char: '🤚', name: 'raised back of hand' },
      { char: '✋', name: 'raised hand' },
      { char: '🖐️', name: 'hand with fingers splayed' },
      { char: '👌', name: 'OK hand' },
      { char: '🤌', name: 'pinched fingers' },
      { char: '🤏', name: 'pinching hand' },
      { char: '✌️', name: 'victory hand' },
      { char: '🤞', name: 'crossed fingers' },
      { char: '🤟', name: 'love-you gesture' },
      { char: '🤘', name: 'sign of the horns' },
      { char: '🤙', name: 'call me hand' },
      { char: '👈', name: 'backhand index pointing left' },
      { char: '👉', name: 'backhand index pointing right' },
      { char: '👆', name: 'backhand index pointing up' },
      { char: '👇', name: 'backhand index pointing down' },
      { char: '☝️', name: 'index pointing up' },
      { char: '👍', name: 'thumbs up' },
      { char: '👎', name: 'thumbs down' },
      { char: '✊', name: 'raised fist' },
      { char: '👊', name: 'oncoming fist' },
      { char: '👏', name: 'clapping hands' },
      { char: '🙌', name: 'raising hands' },
      { char: '🤝', name: 'handshake' },
      { char: '🙏', name: 'folded hands' },
      { char: '✍️', name: 'writing hand' },
      { char: '💪', name: 'flexed biceps' },
      { char: '🧠', name: 'brain' },
      { char: '👀', name: 'eyes' },
      { char: '👶', name: 'baby' },
      { char: '🧒', name: 'child' },
      { char: '👩', name: 'woman' },
      { char: '👨', name: 'man' },
      { char: '🧑', name: 'person' },
      { char: '👵', name: 'old woman' },
      { char: '👴', name: 'old man' },
      { char: '👮', name: 'police officer' },
      { char: '👷', name: 'construction worker' },
      { char: '💂', name: 'guard' },
      { char: '🕵️', name: 'detective' },
      { char: '👩‍⚕️', name: 'health worker' },
      { char: '👩‍🏫', name: 'teacher' },
      { char: '👩‍💻', name: 'technologist' },
      { char: '👩‍🔧', name: 'mechanic' },
      { char: '👩‍🚀', name: 'astronaut' },
      { char: '🎅', name: 'Santa Claus' },
      { char: '🧑‍🎄', name: 'Mx Claus' },
      { char: '🦸', name: 'superhero' },
      { char: '🧙', name: 'mage' },
      { char: '🧚', name: 'fairy' },
      { char: '🤷', name: 'person shrugging' },
      { char: '🤦', name: 'person facepalming' },
      { char: '💁', name: 'person tipping hand' },
      { char: '🙋', name: 'person raising hand' },
      { char: '🙇', name: 'person bowing' },
      { char: '🚶', name: 'person walking' },
      { char: '🏃', name: 'person running' },
      { char: '💃', name: 'woman dancing' },
      { char: '🕺', name: 'man dancing' },
    ],
  },
  {
    name: 'Nature',
    emoji: [
      { char: '🐶', name: 'dog face' },
      { char: '🐱', name: 'cat face' },
      { char: '🐭', name: 'mouse face' },
      { char: '🐹', name: 'hamster' },
      { char: '🐰', name: 'rabbit face' },
      { char: '🦊', name: 'fox' },
      { char: '🐻', name: 'bear' },
      { char: '🐼', name: 'panda' },
      { char: '🐨', name: 'koala' },
      { char: '🐯', name: 'tiger face' },
      { char: '🦁', name: 'lion' },
      { char: '🐮', name: 'cow face' },
      { char: '🐷', name: 'pig face' },
      { char: '🐸', name: 'frog' },
      { char: '🐵', name: 'monkey face' },
      { char: '🐔', name: 'chicken' },
      { char: '🐧', name: 'penguin' },
      { char: '🐦', name: 'bird' },
      { char: '🦆', name: 'duck' },
      { char: '🦉', name: 'owl' },
      { char: '🦇', name: 'bat' },
      { char: '🐺', name: 'wolf' },
      { char: '🐗', name: 'boar' },
      { char: '🐴', name: 'horse face' },
      { char: '🦄', name: 'unicorn' },
      { char: '🐝', name: 'honeybee' },
      { char: '🐛', name: 'bug' },
      { char: '🦋', name: 'butterfly' },
      { char: '🐌', name: 'snail' },
      { char: '🐞', name: 'lady beetle' },
      { char: '🐢', name: 'turtle' },
      { char: '🐍', name: 'snake' },
      { char: '🐙', name: 'octopus' },
      { char: '🦑', name: 'squid' },
      { char: '🦐', name: 'shrimp' },
      { char: '🐠', name: 'tropical fish' },
      { char: '🐟', name: 'fish' },
      { char: '🐬', name: 'dolphin' },
      { char: '🐳', name: 'spouting whale' },
      { char: '🦈', name: 'shark' },
      { char: '🐊', name: 'crocodile' },
      { char: '🐘', name: 'elephant' },
      { char: '🦒', name: 'giraffe' },
      { char: '🦓', name: 'zebra' },
      { char: '🐪', name: 'camel' },
      { char: '🐑', name: 'ewe' },
      { char: '🌵', name: 'cactus' },
      { char: '🌲', name: 'evergreen tree' },
      { char: '🌳', name: 'deciduous tree' },
      { char: '🌴', name: 'palm tree' },
      { char: '🌱', name: 'seedling' },
      { char: '🌿', name: 'herb' },
      { char: '☘️', name: 'shamrock' },
      { char: '🍀', name: 'four leaf clover' },
      { char: '🍁', name: 'maple leaf' },
      { char: '🍂', name: 'fallen leaf' },
      { char: '🌸', name: 'cherry blossom' },
      { char: '🌺', name: 'hibiscus' },
      { char: '🌻', name: 'sunflower' },
      { char: '🌹', name: 'rose' },
      { char: '🌷', name: 'tulip' },
      { char: '🌍', name: 'globe showing Europe-Africa' },
      { char: '🌞', name: 'sun with face' },
      { char: '🌝', name: 'full moon face' },
      { char: '⭐', name: 'star' },
      { char: '🌟', name: 'glowing star' },
      { char: '✨', name: 'sparkles' },
      { char: '⚡', name: 'high voltage' },
      { char: '🔥', name: 'fire' },
      { char: '💧', name: 'droplet' },
      { char: '🌊', name: 'water wave' },
      { char: '☀️', name: 'sun' },
      { char: '⛅', name: 'sun behind cloud' },
      { char: '☁️', name: 'cloud' },
      { char: '🌧️', name: 'cloud with rain' },
      { char: '⛈️', name: 'cloud with lightning and rain' },
      { char: '❄️', name: 'snowflake' },
      { char: '⛄', name: 'snowman' },
      { char: '🌈', name: 'rainbow' },
    ],
  },
  {
    name: 'Food',
    emoji: [
      { char: '🍏', name: 'green apple' },
      { char: '🍎', name: 'red apple' },
      { char: '🍐', name: 'pear' },
      { char: '🍊', name: 'tangerine' },
      { char: '🍋', name: 'lemon' },
      { char: '🍌', name: 'banana' },
      { char: '🍉', name: 'watermelon' },
      { char: '🍇', name: 'grapes' },
      { char: '🍓', name: 'strawberry' },
      { char: '🫐', name: 'blueberries' },
      { char: '🍒', name: 'cherries' },
      { char: '🍑', name: 'peach' },
      { char: '🥭', name: 'mango' },
      { char: '🍍', name: 'pineapple' },
      { char: '🥥', name: 'coconut' },
      { char: '🥝', name: 'kiwi fruit' },
      { char: '🍅', name: 'tomato' },
      { char: '🥑', name: 'avocado' },
      { char: '🥦', name: 'broccoli' },
      { char: '🥕', name: 'carrot' },
      { char: '🌽', name: 'ear of corn' },
      { char: '🌶️', name: 'hot pepper' },
      { char: '🥔', name: 'potato' },
      { char: '🍞', name: 'bread' },
      { char: '🥐', name: 'croissant' },
      { char: '🥖', name: 'baguette' },
      { char: '🧀', name: 'cheese wedge' },
      { char: '🥚', name: 'egg' },
      { char: '🥓', name: 'bacon' },
      { char: '🍔', name: 'hamburger' },
      { char: '🍟', name: 'chips' },
      { char: '🍕', name: 'pizza' },
      { char: '🌭', name: 'hot dog' },
      { char: '🥪', name: 'sandwich' },
      { char: '🌮', name: 'taco' },
      { char: '🌯', name: 'burrito' },
      { char: '🥗', name: 'green salad' },
      { char: '🍝', name: 'spaghetti' },
      { char: '🍜', name: 'steaming bowl' },
      { char: '🍣', name: 'sushi' },
      { char: '🍤', name: 'fried shrimp' },
      { char: '🍚', name: 'cooked rice' },
      { char: '🍰', name: 'shortcake' },
      { char: '🎂', name: 'birthday cake' },
      { char: '🧁', name: 'cupcake' },
      { char: '🍪', name: 'cookie' },
      { char: '🍩', name: 'doughnut' },
      { char: '🍫', name: 'chocolate bar' },
      { char: '🍬', name: 'sweet' },
      { char: '🍯', name: 'honey pot' },
      { char: '🍿', name: 'popcorn' },
      { char: '☕', name: 'hot beverage' },
      { char: '🍵', name: 'teacup' },
      { char: '🧃', name: 'beverage box' },
      { char: '🥤', name: 'cup with straw' },
      { char: '🍺', name: 'beer mug' },
      { char: '🍻', name: 'clinking beer mugs' },
      { char: '🍷', name: 'wine glass' },
      { char: '🥂', name: 'clinking glasses' },
      { char: '🍾', name: 'bottle with popping cork' },
    ],
  },
  {
    name: 'Activity & Travel',
    emoji: [
      { char: '⚽', name: 'football' },
      { char: '🏀', name: 'basketball' },
      { char: '🏈', name: 'american football' },
      { char: '⚾', name: 'baseball' },
      { char: '🎾', name: 'tennis' },
      { char: '🏐', name: 'volleyball' },
      { char: '🏉', name: 'rugby football' },
      { char: '🎱', name: 'pool 8 ball' },
      { char: '🏓', name: 'ping pong' },
      { char: '🏸', name: 'badminton' },
      { char: '🥅', name: 'goal net' },
      { char: '⛳', name: 'flag in hole' },
      { char: '🏹', name: 'bow and arrow' },
      { char: '🎣', name: 'fishing pole' },
      { char: '🥊', name: 'boxing glove' },
      { char: '🎿', name: 'skis' },
      { char: '🛷', name: 'sled' },
      { char: '🏆', name: 'trophy' },
      { char: '🥇', name: 'first place medal' },
      { char: '🥈', name: 'second place medal' },
      { char: '🥉', name: 'third place medal' },
      { char: '🎖️', name: 'military medal' },
      { char: '🎯', name: 'bullseye' },
      { char: '🎲', name: 'game die' },
      { char: '🧩', name: 'puzzle piece' },
      { char: '🎮', name: 'video game' },
      { char: '🎨', name: 'artist palette' },
      { char: '🎬', name: 'clapper board' },
      { char: '🎤', name: 'microphone' },
      { char: '🎧', name: 'headphone' },
      { char: '🎵', name: 'musical note' },
      { char: '🎸', name: 'guitar' },
      { char: '🎹', name: 'musical keyboard' },
      { char: '🥁', name: 'drum' },
      { char: '🎺', name: 'trumpet' },
      { char: '🚗', name: 'car' },
      { char: '🚕', name: 'taxi' },
      { char: '🚌', name: 'bus' },
      { char: '🚑', name: 'ambulance' },
      { char: '🚓', name: 'police car' },
      { char: '🚒', name: 'fire engine' },
      { char: '🚚', name: 'delivery truck' },
      { char: '🚲', name: 'bicycle' },
      { char: '🛵', name: 'motor scooter' },
      { char: '🏍️', name: 'motorcycle' },
      { char: '✈️', name: 'aeroplane' },
      { char: '🚀', name: 'rocket' },
      { char: '🛸', name: 'flying saucer' },
      { char: '🚁', name: 'helicopter' },
      { char: '⛵', name: 'sailboat' },
      { char: '🚢', name: 'ship' },
      { char: '🚂', name: 'locomotive' },
      { char: '🚆', name: 'train' },
      { char: '🗺️', name: 'world map' },
      { char: '🏔️', name: 'snow-capped mountain' },
      { char: '🏝️', name: 'desert island' },
      { char: '🏕️', name: 'camping' },
      { char: '🏠', name: 'house' },
      { char: '🏢', name: 'office building' },
      { char: '🏥', name: 'hospital' },
      { char: '🏫', name: 'school' },
      { char: '🗽', name: 'Statue of Liberty' },
      { char: '🗼', name: 'Tokyo tower' },
      { char: '🎡', name: 'ferris wheel' },
      { char: '🎢', name: 'roller coaster' },
    ],
  },
  {
    name: 'Objects',
    emoji: [
      { char: '⌚', name: 'watch' },
      { char: '📱', name: 'mobile phone' },
      { char: '💻', name: 'laptop' },
      { char: '⌨️', name: 'keyboard' },
      { char: '🖥️', name: 'desktop computer' },
      { char: '🖨️', name: 'printer' },
      { char: '🖱️', name: 'computer mouse' },
      { char: '💾', name: 'floppy disk' },
      { char: '💿', name: 'optical disk' },
      { char: '📷', name: 'camera' },
      { char: '📹', name: 'video camera' },
      { char: '📺', name: 'television' },
      { char: '📻', name: 'radio' },
      { char: '🔋', name: 'battery' },
      { char: '🔌', name: 'electric plug' },
      { char: '💡', name: 'light bulb' },
      { char: '🔦', name: 'torch' },
      { char: '🕯️', name: 'candle' },
      { char: '📞', name: 'telephone receiver' },
      { char: '📧', name: 'e-mail' },
      { char: '📨', name: 'incoming envelope' },
      { char: '📦', name: 'package' },
      { char: '📫', name: 'closed mailbox' },
      { char: '📝', name: 'memo' },
      { char: '📄', name: 'page facing up' },
      { char: '📃', name: 'page with curl' },
      { char: '📑', name: 'bookmark tabs' },
      { char: '📊', name: 'bar chart' },
      { char: '📈', name: 'chart increasing' },
      { char: '📉', name: 'chart decreasing' },
      { char: '📅', name: 'calendar' },
      { char: '📌', name: 'pushpin' },
      { char: '📎', name: 'paperclip' },
      { char: '📏', name: 'straight ruler' },
      { char: '📐', name: 'triangular ruler' },
      { char: '✂️', name: 'scissors' },
      { char: '🗃️', name: 'card file box' },
      { char: '🗑️', name: 'wastebasket' },
      { char: '🔒', name: 'locked' },
      { char: '🔓', name: 'unlocked' },
      { char: '🔑', name: 'key' },
      { char: '🔨', name: 'hammer' },
      { char: '🔧', name: 'wrench' },
      { char: '🔩', name: 'nut and bolt' },
      { char: '⚙️', name: 'gear' },
      { char: '🧲', name: 'magnet' },
      { char: '⚖️', name: 'balance scale' },
      { char: '🔬', name: 'microscope' },
      { char: '🔭', name: 'telescope' },
      { char: '💉', name: 'syringe' },
      { char: '💊', name: 'pill' },
      { char: '🛒', name: 'shopping trolley' },
      { char: '💰', name: 'money bag' },
      { char: '💳', name: 'credit card' },
      { char: '💎', name: 'gem stone' },
      { char: '📚', name: 'books' },
      { char: '📖', name: 'open book' },
      { char: '✏️', name: 'pencil' },
      { char: '🖊️', name: 'pen' },
      { char: '🖍️', name: 'crayon' },
      { char: '🎁', name: 'wrapped gift' },
      { char: '🎈', name: 'balloon' },
      { char: '🎉', name: 'party popper' },
      { char: '🎊', name: 'confetti ball' },
      { char: '🏷️', name: 'label' },
      { char: '🔔', name: 'bell' },
      { char: '⏰', name: 'alarm clock' },
      { char: '⏳', name: 'hourglass' },
    ],
  },
  {
    name: 'Symbols',
    emoji: [
      { char: '❤️', name: 'red heart' },
      { char: '🧡', name: 'orange heart' },
      { char: '💛', name: 'yellow heart' },
      { char: '💚', name: 'green heart' },
      { char: '💙', name: 'blue heart' },
      { char: '💜', name: 'purple heart' },
      { char: '🖤', name: 'black heart' },
      { char: '🤍', name: 'white heart' },
      { char: '💔', name: 'broken heart' },
      { char: '💯', name: 'hundred points' },
      { char: '✅', name: 'check mark button' },
      { char: '☑️', name: 'check box with check' },
      { char: '✔️', name: 'check mark' },
      { char: '❌', name: 'cross mark' },
      { char: '❎', name: 'cross mark button' },
      { char: '➕', name: 'plus' },
      { char: '➖', name: 'minus' },
      { char: '➗', name: 'divide' },
      { char: '✖️', name: 'multiply' },
      { char: '❓', name: 'question mark' },
      { char: '❗', name: 'exclamation mark' },
      { char: '⚠️', name: 'warning' },
      { char: '🚫', name: 'prohibited' },
      { char: '⛔', name: 'no entry' },
      { char: '♻️', name: 'recycling symbol' },
      { char: '🔰', name: 'Japanese symbol for beginner' },
      { char: '⭕', name: 'hollow red circle' },
      { char: '🔴', name: 'red circle' },
      { char: '🟠', name: 'orange circle' },
      { char: '🟡', name: 'yellow circle' },
      { char: '🟢', name: 'green circle' },
      { char: '🔵', name: 'blue circle' },
      { char: '🟣', name: 'purple circle' },
      { char: '⚫', name: 'black circle' },
      { char: '⚪', name: 'white circle' },
      { char: '🟥', name: 'red square' },
      { char: '🟧', name: 'orange square' },
      { char: '🟨', name: 'yellow square' },
      { char: '🟩', name: 'green square' },
      { char: '🟦', name: 'blue square' },
      { char: '⬛', name: 'black square' },
      { char: '⬜', name: 'white square' },
      { char: '🔺', name: 'red triangle pointed up' },
      { char: '🔻', name: 'red triangle pointed down' },
      { char: '🔶', name: 'large orange diamond' },
      { char: '⬆️', name: 'up arrow' },
      { char: '⬇️', name: 'down arrow' },
      { char: '⬅️', name: 'left arrow' },
      { char: '➡️', name: 'right arrow' },
      { char: '↔️', name: 'left-right arrow' },
      { char: '🔄', name: 'counterclockwise arrows' },
      { char: '▶️', name: 'play button' },
      { char: '⏸️', name: 'pause button' },
      { char: '⏹️', name: 'stop button' },
      { char: '🔍', name: 'magnifying glass' },
      { char: '💬', name: 'speech balloon' },
      { char: '💭', name: 'thought balloon' },
      { char: '🗯️', name: 'right anger bubble' },
      { char: '♠️', name: 'spade suit' },
      { char: '♥️', name: 'heart suit' },
      { char: '♦️', name: 'diamond suit' },
      { char: '♣️', name: 'club suit' },
      { char: '™️', name: 'trade mark' },
      { char: '©️', name: 'copyright' },
      { char: '®️', name: 'registered' },
    ],
  },
];

/** Flat list, for the picker's search box. */
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((group) =>
  group.emoji.map((entry) => ({ ...entry, group: group.name })),
);

/** The row shown above the groups; persisted through the settings IPC. */
export const MAX_RECENT_EMOJI = 16;
